baseURL = 'https://breastmed.netlify.app'
languageCode = 'en-gb'
title = 'Dr. Justice Reilly â€” Breastfeeding Medicine'
disableKinds = ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = true
enableGitInfo = true
[markup.goldmark.renderer]
unsafe = true
[imaging]
quality = 80
